### ISSUE TITLE
Error: Failed to fetch access certificate

### ISSUE THREAD

**Issue by lismore** [iotaledger/high-mobility-blueprints#1]
Hi,

I got the following error while attempting to run the application. 

    Error: Failed to fetch access certificate.
     at C:\GitHub\high-mobility- 
    blueprints\charger\node_modules\hmkit\lib\AccessCertificatesManager.js:71:25

Here is a screenshot 

![image](https://user-images.githubusercontent.com/1145888/49378488-a1b93700-f704-11e8-9b72-5cb85c898654.png)

I have all the variables set,

![image](https://user-images.githubusercontent.com/1145888/49378717-3459d600-f705-11e8-8eb9-c52b1220c8ac.png)

The screenshot below shows where it throws the error

![image](https://user-images.githubusercontent.com/1145888/49378615-f78ddf00-f704-11e8-8ad7-fc65a1751534.png)

Running on Windows 7 
node v8.11.4
npm v5.6.0

**Comment by lismore** [comment]
I realised my node/npm needed updated. 

I have updated to 

node v11.2.0 
npm v6.4.1

has had no effect on the issue

**Comment by lismore** [comment]
This response object just before it throws the error, 

    { response:
     Body {
       url:
        'https://high-mobility.com/hm_cloud/api/v1/access_certificates',
       status: 422,
       statusText: 'Unprocessable Entity',
       headers:
        Headers {
          _headers:
           { server: [ 'nginx/1.14.0 (Ubuntu)' ],
             date: [ 'Mon, 03 Dec 2018 15:39:11 GMT' ],
             'content-type': [ 'application/json; charset=utf-8' ],
             'content-length': [ '66' ],
             connection: [ 'close' ],
             'cache-control': [ 'max-age=0, private, must-revalidate' ],
             'x-request-id': [ '2lmdpjimf2kjs7l8g001guk1' ] } },
       ok: false,
       body:
        PassThrough {
          _readableState:
           ReadableState {
             objectMode: false,
             highWaterMark: 16384,
             buffer: BufferList { head: null, tail: null, length: 0 },
             length: 0,
             pipes: null,
             pipesCount: 0,
             flowing: true,
             ended: true,
             endEmitted: true,
             reading: false,
             sync: false,
             needReadable: false,
             emittedReadable: false,
             readableListening: false,
             resumeScheduled: false,
             emitClose: true,
             autoDestroy: false,
             destroyed: false,
             defaultEncoding: 'utf8',
             awaitDrain: 0,
             readingMore: false,
             decoder: null,
             encoding: null },
          readable: false,
          _events:
           [Object: null prototype] {
             prefinish: [Function: prefinish],
             error: [Function],
             data: [Function],
             end: [Function] },
          _eventsCount: 4,
          _maxListeners: undefined,
          _writableState:
           WritableState {
             objectMode: false,
             highWaterMark: 16384,
             finalCalled: false,
             needDrain: false,
             ending: true,
             ended: true,
             finished: true,
             destroyed: false,
             decodeStrings: true,
             defaultEncoding: 'utf8',
             length: 0,
             writing: false,
             corked: 0,
             sync: false,
             bufferProcessing: false,
             onwrite: [Function: bound onwrite],
             writecb: null,
             writelen: 0,
             bufferedRequest: null,
             lastBufferedRequest: null,
             pendingcb: 0,
             prefinished: true,
             errorEmitted: false,
             emitClose: true,
             autoDestroy: false,
             bufferedRequestCount: 0,
             corkedRequestsFree:
              { next: null,
              entry: null,
                finish: [Function: bound onCorkedFinish] } },
          writable: false,
          allowHalfOpen: true,
          _transformState:
           { afterTransform: [Function: bound afterTransform],
             needTransform: false,
             transforming: false,
             writecb: null,
             writechunk: null,
             writeencoding: 'buffer' } },
       bodyUsed: true,
       size: 0,
       timeout: 0,
       _raw:
        [ <Buffer 7b 22 65 72 72 6f 72 73 22 3a 5b 7b 22 74 69 74 6c 65 22 3a 22 49 6e 76 61 6c 69 64 20 52 65 71 75 65 73 74 22 2c 22 64 65 74 61 69 6c 22 3a 22 69 6e ... 16 more bytes> ],
       _abort: false,
       _bytes: 66 },
    json:
     { errors: [ { title: 'Invalid Request', detail: 'invalid_app_id' } ] } }

**Comment by lismore** [comment]
I have added a few logging statements to AccessCertificatesManager.js to see what state some of the variables are in when CASE 7 is triggered.
    signature:SReUplanXYslAiwY6LfxUXdrxYnphKmhPs1Q0T+HddevFKOKqIIUnvkvaF/TOtz/GNf/uLgoOXvM7K43z4h1rw==  

    accessToken: vWjEFvHaK9Wk1ZYFlT-eft4SzOrZ4uoCK9jb6E3nlFnwvYB-kC4nZA7STBlVLwp4i7LsWzwGbuMDXrauR0qNRDjStaPg9REuGTmRcg_QrND1ffgwAZ4TLRcEBxW8Xi4tmw  

    appId:  B6203CDB8CDE045C5E7E239D

I have also used POSTMAN to test the values I see against the endpoint https://high-mobility.com/hm_cloud/api/v1/access_certificates but get the same response http 422 unprocessed entity and invalid request.

**Comment by fijter** [comment]
Hey, sorry for the late response. Thanks for issuing a pull request, it has been merged, I did the same change for the other example so that should be fixed as well.
